name: ci
on:
  push:
    tags:
      - ci-run-*
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        gcc_version: [11]
        linker: [ ld, mold ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install gcc
        run: sudo apt-get install -y gcc-${{ matrix.gcc_version }} g++-${{ matrix.gcc_version }}

      - name: Install mold linker
        uses: rui314/setup-mold@v1
        if: ${{ matrix.linker == 'mold' }}

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.11

      - name: List ccache compilers
        run: |
          ls -l /usr/lib/ccache

      - name: Set up Python 3.8.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        env:
          CC:   /usr/lib/ccache/gcc-${{ matrix.gcc_version }}
          CXX:  /usr/lib/ccache/g++-${{ matrix.gcc_version }}
        with:
          build-dir: build
          options: CMAKE_BUILD_TYPE=Debug BUILD_EXAMPLE=ON BUILD_TESTS=ON

      - name: Build Project
        run: |
          cmake --build build -j $(nproc) 
          readelf -p .comment build/example/eprofiler_example

      - name: Run Tests
        run: |
          ctest --test-dir build